ImplicitWaitTime = driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
reportConfigPath=C:/Users/2254513/Downloads/Git/SeleniumTestNG/configs/spark-config.xml
reportOutPath=C:/Users/2254513/Downloads/Git/SeleniumTestNG/target/Spark.html
baseURL=https://anupdamoda.github.io/AceOnlineShoePortal/index.html
#BSuserName=sathishponnusamy_yQ8Y0R
#BSpassWord=yyxPBXzPZhsqhzuNmPGs
BSURL=https://sathishponnusamy_yQ8Y0R:yyxPBXzPZhsqhzuNmPGs@hub.cloud.browserstack.com/wd/hub

