# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
#    - run: mvn clean test
#    - run: mvn clean test -DTest="apiAutomation"

    - name: Run API test only
      run: mvn clean test -Dtest=apiAutomation -DexcludeTests=RunCucumberTest

    - name: Test Artefact Upload
      uses: actions/upload-artifact@v4
      with:
        name: TestReport
        path: /home/runner/work/SeleniumTestNG/SeleniumTestNG/**

          # ⬇️ Upload cucumber report artifact
    - name: Upload Cucumber Report
      uses: actions/upload-artifact@v4
      with:
          name: cucumber-report
          path: /home/runner/work/SeleniumTestNG/SeleniumTestNG/target/**
          retention-days: 7
          
    - name: Verify Report Files Exist
      run: ls -R target/
  
# Upload the Extent Report Artifact
    - name: Upload Extent Reports
      uses: actions/upload-artifact@v4
      with:
          # This is the name the artifact will have in the GitHub UI
          name: Extent-HTML-Report
          
          # This is the path to the directory containing your report file(s).
          # Use a path that includes all necessary assets (JS, CSS, images) 
          # which are usually in the directory alongside index.html.
          path: |
            target/ # Adjust this path to your actual report directory
            target/* # Include all files recursively
            
          # (Optional) Define how long the artifact should be retained (in days). Max 90 days.
          retention-days: 30 
          
      # 4. Optional: Run this step even if tests fail
      # This ensures you get the report for debugging failures.
      if: always()          
